/**
 * AI-002 & AI-018: Application-owned Candidate Typed Analytical Plan.
 * This represents the candidate output generated by the AI provider.
 * It is strictly separated from server-owned execution controls (ExecutionEnvelope)
 * and parameterized SQL compilation (Application-Owned AST).
 */
export interface CandidateQueryIntent {
  intentType: "AGGREGATION" | "FILTER" | "TREND" | "COMPARISON" | "UNKNOWN";
  primaryEntity: string;
  dimensions: string[];
  metrics: string[];
  filters?: Array<{
    field: string;
    operator: "=" | "!=" | ">" | "<" | ">=" | "<=" | "IN" | "LIKE";
    value: string | number | boolean | Array<string | number>;
  }>;
  timeRange?: {
    startDate?: string;
    endDate?: string;
    granularity?: "DAY" | "WEEK" | "MONTH" | "QUARTER" | "YEAR";
  };
  limit?: number;
}

export interface ModelCandidatePlan {
  planId: string;
  candidateIntents: CandidateQueryIntent[];
  confidenceScore: number;
  reasoningSummary?: string;
  suggestedVisualization?: "TABLE" | "BAR_CHART" | "LINE_CHART" | "KPI_CARD" | "PIE_CHART";
  isFallback: boolean;
}

/**
 * Token budget controls for application-enforced cost and rate management.
 */
export interface AITokenBudget {
  maxInputTokens?: number;
  maxOutputTokens?: number;
  maxConversationTokens?: number;
}

/**
 * Application-owned request context passed to the AI Provider Interface.
 * Provider SDK request objects must not leak into domain services.
 */
export interface AIProviderRequest {
  prompt: string;
  systemInstruction?: string;
  context?: {
    userId?: number;
    roleId?: string;
    tenantId?: string;
    locale?: string;
    allowedEntities?: string[];
  };
  tokenBudget?: AITokenBudget;
  temperature?: number;
}

/**
 * Normalized telemetry collected for operational observability, cost tracking,
 * and persistence in model_usage.
 */
export interface AIUsageTelemetry {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  latencyMs: number;
  providerName: string;
  modelName: string;
  modelVersion?: string;
  region?: string;
  estimatedCostUsd?: number;
  retryCount: number;
}

/**
 * Application-owned response structure returned to domain services.
 */
export interface AIProviderResponse {
  candidatePlan: ModelCandidatePlan;
  narrative?: string;
  usage: AIUsageTelemetry;
  fromFallback: boolean;
  fallbackReason?: string;
  rawResponseText?: string;
}

/**
 * AI-015: Provider Failure Classification Taxonomy.
 * Isolates provider-specific SDK exceptions into application-defined error categories.
 */
export type AIErrorCategory =
  | "TRANSIENT_FAILURE"
  | "TIMEOUT"
  | "UNAVAILABLE"
  | "REJECTED"
  | "RATE_LIMITED"
  | "INVALID_RESPONSE"
  | "CONFIG_ERROR"
  | "TOKEN_BUDGET_EXCEEDED";

export class AIProviderException extends Error {
  public readonly category: AIErrorCategory;
  public readonly providerName: string;
  public readonly isTransient: boolean;
  public readonly originalError?: any;

  constructor(
    category: AIErrorCategory,
    message: string,
    providerName: string = "UNKNOWN",
    originalError?: any,
  ) {
    super(message);
    this.name = "AIProviderException";
    this.category = category;
    this.providerName = providerName;
    this.isTransient =
      category === "TRANSIENT_FAILURE" ||
      category === "TIMEOUT" ||
      category === "RATE_LIMITED";
    this.originalError = originalError;

    Object.setPrototypeOf(this, AIProviderException.prototype);
  }
}
